---
name: Self-hosted Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1.10.0
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: .github/copier-renovate.json5
          docker-cmd-file: .github/entrypoint.sh
          docker-user: root
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
